# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9dcfa24f1393f60eac7b9a8f82c25a0b6c6b83ba4919a4b1c9bb75131b68aaafc08a5c265bdf2c49887522ce67e31f5ff3598a13a19d912ee93cb13e8bae3555

test:
  secret_key_base: c7405127bcd76550cf42b12c37b448ac8b9dc1c9a694a48fb4d6303dc8fd3e1ba5c9e3df65f5925a030f592970b85fffa6f26c90b6f370deb57238295f1f36b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
